/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keepshare_breakpadcreate_BreakPadManager */

#ifndef _Included_com_keepshare_breakpadcreate_BreakPadManager
#define _Included_com_keepshare_breakpadcreate_BreakPadManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_keepshare_breakpadcreate_BreakPadManager
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_keepshare_breakpadcreate_BreakPadManager_init
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
